input {
  file {
    path => "/var/log/app/app*.log"  # 컨테이너 내부로 마운트된 모든 적재 로그 파일 경로 + 백업 파일들까지
#   path => "/var/log/app/app.log"   # 컨테이너 내부로 마운트된 실시간 적재 로그 파일 경로
    start_position => "beginning"    # 파일 처음부터 읽기
    sincedb_path => "/dev/null"      # 실습 시 재시작해도 로그를 처음부터 다시 읽도록 설정
    # Logstash 설정을 계속 수정하면서 컨테이너를 재시작할텐데 한번 읽은 로그라도 처음부터 다시 읽도록하여 ES 내 처음부터 모든 로그가 적재되도록 -> Kibana 확인 용이하게

    codec => multiline {
      pattern => "^\d{4}-\d{2}-\d{2}"
      negate => "true"
      what => "previous"
    }
  }
}

filter {
  # 필요 시 grok 등으로 텍스트 로그 파싱 가능 (실습 시 생략 가능)
  # 1. Grok 필터를 사용하여 통문자열 로그를 개별 필드로 정교하게 분리
  grok {
    match => {
      # client_ip 와 user_id 는 있을 수도, 없을 수도 있으므로 옵셔널(? 사용)로 가공
      "message" => "%{TIMESTAMP_ISO8601:log_time}\s+\[%{DATA:thread}\]\s+%{LOGLEVEL:log_level}\s+%{NOTSPACE:logger}\s+(?:\[%{IP:client_ip}\]\s+)?(?:\[%{DATA:user_id}\]\s+)?-\s+%{GREEDYDATA:log_message}"
    }
  }
  # 2. 지저분한 원본 메타데이터 및 빈 필드 정리
  mutate {
    remove_field => [ "event", "host", "@version", "message", "log" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Logstash 컨테이너 콘솔에도 파싱 결과 출력 (확인용)
}