spring.application.name=demo

logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.com.example.demo.controller=TRACE
# 패키지 별로 로깅 레벨 설정이 가능해서 필요한 부분에 대해서만 세부적인 로그 확인이 가능하다
# logging.level.org.springframework=WARN
# logging.level.org.hibernate.SQL=DEBUG

# Prometheus 엔드포인트 열기
server.port=8080
management.server.port=7070
management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.tags.application=${spring.application.name:spring-boot-app}
